//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkbilYonetimiUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Akbil : global::System.Configuration.ApplicationSettingsBase {
        
        private static Akbil defaultInstance = ((Akbil)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Akbil())));
        
        public static Akbil Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BeniHatirla {
            get {
                return ((bool)(this["BeniHatirla"]));
            }
            set {
                this["BeniHatirla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BeniHatirlaKullaniciEmail {
            get {
                return ((string)(this["BeniHatirlaKullaniciEmail"]));
            }
            set {
                this["BeniHatirlaKullaniciEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BeniHatirlaKullaniciSifre {
            get {
                return ((string)(this["BeniHatirlaKullaniciSifre"]));
            }
            set {
                this["BeniHatirlaKullaniciSifre"] = value;
            }
        }
    }
}
